# Generated by Django 5.2.8 on 2025-11-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('admin_mini', 'Admin Mini'), ('teacher', 'Teacher')], default='teacher', max_length=20, verbose_name='Foydalanuvchi roli'),
        ),
    ]
