# Generated by Django 5.2.8 on 2025-11-25 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_center_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(80)], verbose_name='Yosh'),
        ),
        migrations.AddField(
            model_name='user',
            name='pinfl',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='PINFL'),
        ),
        migrations.AddField(
            model_name='user',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fan'),
        ),
        migrations.AddField(
            model_name='user',
            name='teacher_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='user',
            name='teacher_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', "Telefon raqam noto'g'ri formatda")], verbose_name='Telefon raqam'),
        ),
    ]
