# Generated by Django 5.2.8 on 2025-11-17 12:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', 'Telefon raqam noto‘g‘ri formatda')], verbose_name='Telefon raqam')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('director', models.CharField(max_length=255, verbose_name='Direktor')),
            ],
            options={
                'verbose_name': 'O‘quv markaz',
                'verbose_name_plural': 'O‘quv markazlar',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('body', models.TextField(verbose_name='Matn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='core.learningcenter', verbose_name='O‘quv markaz')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', 'Telefon raqam noto‘g‘ri formatda')], verbose_name='Telefon raqam')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('workplace', models.CharField(max_length=255, verbose_name='Ish joyi')),
                ('relationship', models.CharField(max_length=50, verbose_name='Qarindoshlik')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.learningcenter', verbose_name='O‘quv markaz')),
            ],
            options={
                'verbose_name': 'Ota-ona',
                'verbose_name_plural': 'Ota-onalar',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('age', models.PositiveIntegerField(verbose_name='Yosh')),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', 'Telefon raqam noto‘g‘ri formatda')], verbose_name='Telefon raqam')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('subject', models.CharField(max_length=100, verbose_name='Fan')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.learningcenter', verbose_name='O‘quv markaz')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.parent', verbose_name='Ota-ona')),
            ],
            options={
                'verbose_name': 'O‘quvchi',
                'verbose_name_plural': 'O‘quvchilar',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miqdor')),
                ('deadline', models.DateField(verbose_name='To‘lov sanasi')),
                ('status', models.CharField(max_length=50, verbose_name='To‘lov holati')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Admin mini')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='O‘quvchi')),
            ],
            options={
                'verbose_name': 'To‘lov',
                'verbose_name_plural': 'To‘lovlar',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(80)], verbose_name='Yosh')),
                ('pinfl', models.CharField(max_length=14, verbose_name='PINFL')),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', 'Telefon raqam noto‘g‘ri formatda')], verbose_name='Telefon raqam')),
                ('subject', models.CharField(max_length=100, verbose_name='Fan')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='core.learningcenter', verbose_name='O‘quv markaz')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi (O‘qituvchi)')),
            ],
            options={
                'verbose_name': 'O‘qituvchi',
                'verbose_name_plural': 'O‘qituvchilar',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.teacher', verbose_name='O‘qituvchi'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Fan')),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Baho')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('date', models.DateField(verbose_name='Sana')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='O‘quvchi')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher', verbose_name='O‘qituvchi')),
            ],
            options={
                'verbose_name': 'Baholash',
                'verbose_name_plural': 'Baholar',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_1', models.BooleanField(default=False, verbose_name='Dars 1')),
                ('lesson_2', models.BooleanField(default=False, verbose_name='Dars 2')),
                ('lesson_3', models.BooleanField(default=False, verbose_name='Dars 3')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='O‘quvchi')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher', verbose_name='O‘qituvchi')),
            ],
            options={
                'verbose_name': 'Davomat',
                'verbose_name_plural': 'Davomatlar',
            },
        ),
    ]
