# Generated by Django 5.2.8 on 2025-12-04 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_learningcenter_is_active_news_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('due_date', models.DateField(verbose_name='Muddati')),
                ('homework_file', models.FileField(blank=True, null=True, upload_to='homeworks/', verbose_name='Fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='core.learningcenter', verbose_name="O'quv markaz")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_homeworks', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan admin')),
                ('students', models.ManyToManyField(blank=True, related_name='homeworks', to='core.student', verbose_name="O'quvchilar")),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_homeworks', to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Uy vazifasi',
                'verbose_name_plural': 'Uy vazifalari',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
    ]
